### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by Mateo-714** [EQUIPO4ppi/equipo04_fbm_ppi2020#3]
En la actualidad existe una gran falta de información acerca de los eventos que se realizan en la comunidad del barrio Florencia. Esta falta de informaciòn yace en que los vecinos no cuentan con el tiempo suficiente para interactuar entre sí, y al momento de intentarlo, la falta de confianza genera o un ambiente de tensiòn o un desinterés para comunicar algo.Los eventos realizados en este sector puede beneficiar a una gran cantidad de personas, pero pese a que los organizadores y administradores de los eventos se encargan de informar a travès de carteles y de tú a tú, la informaciòn muchas veces no llega a recoger la magnitud de población que se necesita para mantener estable un evento o para satisfacer la intensiòn de los organizadores. La consecuencia de esto último, es el desaparecimiento de estos eventos en la comunidad, haciendo que las pocas personas que lo utilizaban y les causaba algùn beneficio lo pierdan y se vean afectadas. Otra consecuencia de esto es que los eventos culturales se van perdiendo cada vez màs en la comunidad y produce desculturizaciòn en la juventud de la comunidad.

**Comment by marthaduque** [comment]
el nombre de la actividad debe comenzar con un verbo en infinitivo y adicionar label.
