### ISSUE TITLE
Identificar y describir interesados

### ISSUE THREAD

**Issue by Mateo-714** [EQUIPO4ppi/equipo04_fbm_ppi2020#4]
- Habitantes del barrio florencia
Usuario interesado en obtener información acerca de los eventos

-Directivos de la acción comunal
Cliente a quien le interesa proporcionar de una manera efectiva la información de sus próximos eventos

**Comment by marthaduque** [comment]
el nombre de la actividad debe comenzar con un verbo en infinitivo y adicionar label.

**Comment by marthaduque** [comment]
el nombre de la actividad debe comenzar con un verbo en infinitivo y adicionar label.

**Comment by marthaduque** [comment]
el nombre de la actividad debe comenzar con un verbo en infinitivo y adicionar label y responsables.
